mqtt:
  - sensor:
      name: "data"
      state_topic: "/I102/CoudraisGirardin/data"
      suggested_display_precision: 1
  - sensor:
      name: "temp"
      state_topic: "/I102/CoudraisGirardin/temp"
      suggested_display_precision: 1
automation: !include automations.yaml