version: '3.7'

# rebuild image pour $HOME

services:

  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /tmp/docker_volumes/homeAssistant/config:/config
    restart: unless-stopped


  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto_broker
    restart: always
    ports:
      - "1884:1884"
      - "9001:9001"
    volumes:
      - /tmp/docker_volumes/mosquitto/config:/mosquitto/config
      - /tmp/docker_volumes/mosquitto/data:/mosquitto/data
      - /tmp/docker_volumes/mosquitto/log:/mosquitto/log  
